name: order_server
description: Simple CQRS backend service for E-Shoppe.
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  uuid: ^4.2.0
  json_annotation: ^4.8.1
  postgres: ^2.6.4
  dart_jsonwebtoken: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1 