name: Android Release

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: 'Build number (int)'
        required: true
        default: '1'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Restore pub cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Generate launcher icons & splash
        run: |
          flutter pub run flutter_launcher_icons
          flutter pub run flutter_native_splash:create

      - name: Decode keystore
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          echo $ANDROID_KEYSTORE_BASE64 | base64 -d > android/app/release.keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create key.properties
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          printf "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}\nkeyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}\nkeyAlias=${{ secrets.ANDROID_KEY_ALIAS }}\nstoreFile=release.keystore" > android/key.properties

      - name: Build AAB
        run: flutter build appbundle --release --build-number ${{ inputs.build_number }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab 