name: iOS Release

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: 'Build number (int)'
        required: true
        default: '1'

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Restore pub cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Generate icons & splash
        run: |
          flutter pub run flutter_launcher_icons
          flutter pub run flutter_native_splash:create

      # If signing files are provided, decode them
      - name: Prepare provisioning profile
        if: ${{ secrets.IOS_PROFILE_BASE64 != '' }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo $IOS_PROFILE_BASE64 | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
        env:
          IOS_PROFILE_BASE64: ${{ secrets.IOS_PROFILE_BASE64 }}

      - name: Prepare certificates
        if: ${{ secrets.IOS_CERT_BASE64 != '' }}
        run: |
          echo $IOS_CERT_BASE64 | base64 -d > cert.p12
          security create-keychain -p "temp" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "temp" build.keychain
          security import cert.p12 -k build.keychain -P $IOS_CERT_PASSWORD -T /usr/bin/codesign
        env:
          IOS_CERT_BASE64: ${{ secrets.IOS_CERT_BASE64 }}
          IOS_CERT_PASSWORD: ${{ secrets.IOS_CERT_PASSWORD }}

      - name: Build IPA
        run: |
          flutter build ipa --release --build-number ${{ inputs.build_number }} --export-options-plist ios/Runner/ExportOptions.plist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/ipa/*.ipa 